- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
  
  
    - set_fact:
        random_name: "sdia_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
        
    
    - ec2_vpc:
        state: present
        cidr_block: 172.23.0.0/16
        region: "{{region}}"
      register: ec2_vpc
      
      
    - local_action: copy content={{ ec2_vpc }} dest=/tmp/ec2_vpc.json
