- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:  
        
  
    - local_action: copy content={{ item.value }} dest=/tmp/{{ item.name }}.json
      with_items:
        - { name: "{{random_name}}_ec2_vms", value: "{{ vm }}" }        
        - { name: "{{random_name}}_ec2_ssh_keys", value: "{{ ssh_keys }}" }      
        - { name: "{{random_name}}_ec2_instances", value: "{{ hostvars['localhost']['instances'] }}" }
        
        

    - shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_ec2_ssh_keys.json  /tmp/{{random_name}}_ec2_vms.json > /tmp/{{random_name}}_ec2_ssh_keys_vms.json  
    - shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_ec2_ssh_keys_vms.json  /tmp/{{random_name}}_ec2_instances.json > /tmp/{{random_name}}_ec2_attributes.json  
      
    - include_vars:
        file: /tmp/{{random_name}}_ec2_attributes.json
        name: attributes
                     
        
    - include_tasks: create_user.yaml
      vars: 
        ssh_keys: "{{ item.value['user_key_pair']['keys'] }}"
        default_user: ubuntu
        user_name:  "{{ item.value['user_name'] }}"
      loop: "{{ attributes | dict2items }}"
