- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
  
  
    - set_fact:
        random_name: "sdia_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
        
    
    - ec2_vpc_net:
        name: "{{random_name}}"
        state: present
        cidr_block: 172.23.0.0/16
        region: "{{region}}"
        tenancy: dedicated
      register: ec2_vpc_output


    - debug:
        var: ec2_vpc_output
      
      
    - local_action: copy content={{ ec2_vpc_output }} dest=/tmp/ec2_vpc_output.json


    - include_tasks: vpc.yaml
      vars:
        instance_name: "{{ item.key }}"
      loop: "{{ instances | dict2items }}"