- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - ec2_group:
        name: "{{random_name}}"
        description: sdia generated
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        state: absent
      register: group_output
      
    - local_action: copy content={{ group_output }} dest=/tmp/"{{random_name}}"_ec2_group_output.json
        
        
    - set_stats:
        data:
          security_group_name: "{{ random_name }}"
