- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - package:
        name:
        - jq
        state: present


    - pip:
        name:
          - boto3
    - shell: ansible-galaxy collection install amazon.aws
