- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - ec2_group:
        name: "{{random_name}}"
        description: sdia generated
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        - proto: all
          # in the 'proto' attribute, if you specify -1, all, or a protocol number other than tcp, udp, icmp, or 58 (ICMPv6),
          # traffic on all ports is allowed, regardless of any ports you specify
          from_port: 10050 # this value is ignored
          to_port: 10050 # this value is ignored
          cidr_ip: 0.0.0.0/0
      register: group_output
      
    - local_action: copy content={{ group_output }} dest=/tmp/"{{random_name}}"_ec2_group_output.json
        
 
#     - include_tasks: security_group.yaml
#       vars:
#         instance_name: "{{ item.key }}"
#       loop: "{{ instances | dict2items }}"
      
#     - shell: jq '{"{{topology_name}}":{resource_group:.state.name}}' /tmp/"{{random_name}}"_ec2_group_output.json > /tmp/"{{random_name}}"_ec2_group_attribute.json
    
#     - include_vars:
#         file: /tmp/"{{random_name}}"_ec2_group_attribute.json
#         name: resourcegroup_attribute
        
    - set_stats:
        data:
          security_group_name: "{{ random_name }}"
          
#     - set_stats:
#         data: 
#           resourcegroup_attribute: "{{resourcegroup_attribute}}"
