- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - ec2_group:
        name: "{{random_name}}"
        description: sdia generated
        vpc_id: "{{vpc_id}}"
        region: "{{region_name}}"

      
    - local_action: copy content={{ group_output }} dest=/tmp/group_output.json
        
 
    - include_tasks: security_group.yaml
      vars:
        instance_name: "{{ item.key }}"
      loop: "{{ instances | dict2items }}"
      
    - shell: jq '{"{{topology_name}}":{resource_group:.state.name}}' /tmp/resourcegroup_output.json > /tmp/resourcegroup_attribute.json
    
    - include_vars:
        file: /tmp/resourcegroup_attribute.json
        name: resourcegroup_attribute
        
    - set_stats:
        data:
          resource_group_name: "{{ random_name }}"
          
    - set_stats:
        data: 
          resourcegroup_attribute: "{{resourcegroup_attribute}}"
