- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:  
  
  
  
    - local_action: copy content={{ item.value }} dest=/tmp/{{ item.name }}.json
      with_items:
        - { name: "{{random_name}}"_ec2_selected_flavors, value: "{{ selected_flavors }}" }
        - { name: "{{random_name}}"_ec2_ssh_keys, value: "{{ ssh_keys }}" }
        - { name: "{{random_name}}"_ec2_networks, value: "{{ networks }}" }
        - { name: "{{random_name}}"_ec2_instances, value: "{{ hostvars['localhost']['instances'] }}" }
        - { name: "{{random_name}}"_ec2_images, value: "{{ images }}" }
        
        

    - shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_ec2_selected_flavors.json /tmp/ssh_keys.json > /tmp/{{random_name}}_ec2_flavors_ssh_keys.json
    - shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_ec2_networks.json /tmp/{{random_name}}_ec2_flavors_ssh_keys.json > /tmp/{{random_name}}_ec2_networks_flavors_ssh_keys.json
    - shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_ec2_instances.json /tmp/{{random_name}}_ec2_networks_flavors_ssh_keys.json > /tmp/{{random_name}}_ec2_networks_flavors_ssh_keys_instances.json
    - shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_ec2_images.json /tmp/{{random_name}_ec2}_networks_flavors_ssh_keys_instances.json > /tmp/{{random_name}}_ec2_vms.json
    
  
    - include_vars:
        file: /tmp/{{random_name}}_ec2_vms.json
        name: vms
        
        
    - include_tasks: vm.yaml
      vars: 
        ssh_key_name: "{{ item.value['user_key_pair']['keys']['name'] }}"
        security_group_name: "{{item.value['security_group_name']}}"
        flavor: "{{item.value['flavor_name']}}"
        image_id: "{{item.value['image_id']}}"
        subnet_id: "{{item.value['subnet_id']}}"
      loop: "{{ vms | dict2items }}"
