- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:  
         
    - include_tasks: delete_vm.yaml
      vars: 
        image_id: "{{item.value['id']}}"
        state: absent
      loop: "{{ hostvars['localhost']['instances'] | dict2items }}"
