- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - ec2_key:
        name: "{{random_name}}"
        region: "{{region}}"
      register: key_output

    - local_action: copy content={{ key_output }} dest=/tmp/{{random_name}}_key_output.json

    - include_tasks: create_key.yaml
      vars:
        instance_name: "{{ item.key }}"
      loop: "{{ instances | dict2items }}"
