- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - set_fact:
        random_name: "sdia_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
        
    - ec2_key:
        name: "{{random_name}}"
                
    - include_tasks: create_key.yaml
      vars:
        instance_name: "{{ item.key }}"
        name: "{{random_name}}"
      loop: "{{ instances | dict2items }}"
