- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - ec2_key:
        name: "{{random_name}}"
        region: "{{region}}"
        state: absent
        
      
    - set_stats:
        data: 
          random_name: "{{random_name}}"
