- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    
    - ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_id}}"
        cidr: 172.23.0.0/16
        region: "{{region}}"
      register: subnet_output

    - local_action: copy content={{ subnet_output }} dest=/tmp/{{random_name}}_ec2_subnet_output.json


#     - include_tasks: vpc_subnet.yaml
#       vars:
#         instance_name: "{{ item.key }}"
#       loop: "{{ instances | dict2items }}"

    - shell: jq -r '.subnet.id' /tmp/{{random_name}}_ec2_subnet_output.json
      register: ec2_subnet_id

    - set_stats:
        data:
          vpc_id: "{{ ec2_subnet_id.stdout }}"
