- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    
    - ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_id}}"
        cidr: 172.23.0.0/16
        region: "{{region}}"
        wait: yes
        tags:
          Name: "{{random_name}}"
      register: subnet_output

    - local_action: copy content={{ subnet_output }} dest=/tmp/{{random_name}}_ec2_subnet_output.json


    - shell: jq -r '.| {subnet_id:.subnet.id}' /tmp/{{random_name}}_ec2_subnet_output.json
      register: ec2_subnet_id

    - set_stats:
        data:
          subnet_id: "{{ ec2_subnet_id.stdout }}"
          
          
    - ec2_vpc_subnet_facts:
        region: "{{ region }}"
        filters:
          vpc-id: "{{vpc_id}}"
          subnet-id: "{{ subnet_id }}"
        register: ec2_vpc_subnet_facts_out
        
    - debug:
        var: ec2_vpc_subnet_facts    - name: get facts
      ec2_vpc_subnet_facts:
        aws_access_key: "{{ sts_aws_access_key | default(omit) }}"
        aws_secret_key: "{{ sts_aws_secret_key | default(omit) }}"
        security_token: "{{ sts_security_token | default(omit) }}"  
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc }}"
          subnet-id: "{{ subnet }}"
      

#     - include_tasks: vpc_subnet.yaml
#       vars:
#         instance_name: "{{ item.key }}"
#       loop: "{{ instances | dict2items }}"
