- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    
    - ec2_vpc_net:
        name: "{{random_name}}"
        state: absent
        cidr_block: 172.23.0.0/16
        region: "{{region}}"
