- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - include_tasks: get_image.yaml
      vars:
        os_distro: "{{ item.value.os_distro }}"
        os_version: "{{ item.value.os_version }}"
        domain: "{{region}}"
      loop: "{{ hostvars['localhost']['instances'] | dict2items }}"





